const countrys = [
  {
    id: 1,
    name: "United states of Amerika",
    capital: "Vashington",
    population: 11750,
    flag: "./images/usa.gif",
    isLike:false,
    isSaved:false,
  },
  {
    id: 2,
    name: "Portugal",
    capital: "Lissabon",
    population: 366425,
    flag: "./images/portugal.gif",
    isLike:false,
    isSaved:false,
  },
  {
    id: 3,
    name: "Germany",
    capital: "Berlin",
    population: 20250834,
    flag: "./images/germany.gif",
    isLike:false,
    isSaved:false,
  },
  {
    id: 4,
    name: "Palestine",
    capital: "East Jerusalem",
    population: 869595,
    flag: "./images/palestine.gif",
    isLike:false,
    isSaved:false,
  },
  {
    id: 5,
    name: "Turkey",
    capital: "Ankara",
    population: 25687041,
    flag: "./images/turkey.gif",
    isLike:false,
    isSaved:false,
  },
  {
    id: 6,
    name: "Russian",
    capital: "Moskva",
    population: 38005238,
    flag: "./images/russia.gif",
    isLike:false,
    isSaved:false,
  },
  {
    id: 7,
    name: "Uzbekistan",
    capital: "Tashkent",
    population: 9398861,
    flag: "./images/uzb.gif",
    isLike:false,
    isSaved:false,
  },
  {
    id: 8,
    name: "Saudia Arabia",
    capital: "Al-Riyadh",
    population: 786559,
    flag: "./images/arab.gif",
    isLike:false,
    isSaved:false,
  },
];
